vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO TuxedoFish/hyperliquid-sdk-cpp
    REF "v${VERSION}"
    SHA512 796dd1a11a2834786caafd81020b544ca5de30c4a26774cc295dd06777f9643620bd398f91a1b575055368b4ebe4c73524a641847f27f4e99b5d55c06e8ee1d7
    HEAD_REF main
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DHYPERLIQUID_BUILD_EXAMPLES=OFF
        -DHYPERLIQUID_BUILD_TESTS=OFF
        -DHYPERLIQUID_BUILD_FUZZERS=OFF
        -DHYPERLIQUID_WARNINGS_AS_ERRORS=OFF
        -DHYPERLIQUID_SANITIZE=OFF
        -DHYPERLIQUID_COVERAGE=OFF
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/hyperliquid-sdk)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
